20 integrate address search results
Geovation/usemap-reactjs pull request #33
Opened 2022-10-05 12:40 UTC by branmkam

2022-10-06 09:52 UTC, DaveBathnes requested changes

2022-10-06 11:00 UTC, branmkam commented
Check it now - utils should be good to go.

2022-10-12 13:40 UTC, DaveBathnes requested changes

2022-10-12 13:40 UTC, DaveBathnes commented on src/hooks/usePlaces.js
> +  const [loading, setLoading] = useState(true)
I'm assuming this should be false when the hook is initialised. Then it's true when seachPlaces is run,and then false when searchPlaces returns data?

2022-10-18 12:52 UTC, branmkam commented on src/hooks/usePlaces.js
> +  const [loading, setLoading] = useState(true)
Just fixed it - my bad for missing this earlier.

2022-10-18 13:21 UTC, DaveBathnes approved these changes

2022-10-18 15:30 UTC, merged